"""empty message

Revision ID: 00fee616c89f
Revises: 3352b6a9f80e
Create Date: 2022-07-04 18:12:36.290284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00fee616c89f'
down_revision = '3352b6a9f80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('post_user', 'posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_user', 'posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('like')
    # ### end Alembic commands ###
