"""empty message

Revision ID: 3352b6a9f80e
Revises: 202ade5a33a3
Create Date: 2022-07-02 22:03:30.160762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3352b6a9f80e'
down_revision = '202ade5a33a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_user', sa.Column('post_title', sa.String(length=150), nullable=False))
    op.drop_constraint('post_user_post_name_key', 'post_user', type_='unique')
    op.create_unique_constraint(None, 'post_user', ['post_title'])
    op.drop_column('post_user', 'post_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_user', sa.Column('post_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_user', type_='unique')
    op.create_unique_constraint('post_user_post_name_key', 'post_user', ['post_name'])
    op.drop_column('post_user', 'post_title')
    # ### end Alembic commands ###
