"""empty message

Revision ID: 7d759285c1d0
Revises: d6713024dee8
Create Date: 2022-07-04 18:16:56.467385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d759285c1d0'
down_revision = 'd6713024dee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('like_number', sa.Integer(), nullable=True))
    op.drop_column('like', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('like', 'like_number')
    # ### end Alembic commands ###
