"""empty message

Revision ID: 845732793c1e
Revises: cb2b20b163a9
Create Date: 2022-07-07 20:41:11.154720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845732793c1e'
down_revision = 'cb2b20b163a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('like')
    op.add_column('profile', sa.Column('platform', sa.String(length=50), nullable=False))
    op.drop_constraint('profile_favorite_games_key', 'profile', type_='unique')
    op.drop_constraint('profile_region_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_region_key', 'profile', ['region'])
    op.create_unique_constraint('profile_favorite_games_key', 'profile', ['favorite_games'])
    op.drop_column('profile', 'platform')
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_user.id'], name='like_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['profile.id'], name='friends_user_from_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='friends_pkey')
    )
    # ### end Alembic commands ###
