"""empty message

Revision ID: a4ffbd2d8f86
Revises: f6832627acfb
Create Date: 2022-06-29 02:02:54.560372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ffbd2d8f86'
down_revision = 'f6832627acfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.add_column('profile', sa.Column('favorite_games', sa.String(length=50), nullable=False))
    op.add_column('profile', sa.Column('region', sa.String(length=50), nullable=False))
    op.add_column('profile', sa.Column('contact', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'profile', ['region'])
    op.create_unique_constraint(None, 'profile', ['contact'])
    op.create_unique_constraint(None, 'profile', ['favorite_games'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'contact')
    op.drop_column('profile', 'region')
    op.drop_column('profile', 'favorite_games')
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('game_modes', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('release_dates', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='games_pkey'),
    sa.UniqueConstraint('name', name='games_name_key')
    )
    # ### end Alembic commands ###
