"""empty message

Revision ID: d6713024dee8
Revises: 00fee616c89f
Create Date: 2022-07-04 18:14:33.030582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6713024dee8'
down_revision = '00fee616c89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'like')
    # ### end Alembic commands ###
