"""empty message

Revision ID: e3ae51a0b5a9
Revises: e966c837caf5
Create Date: 2022-07-07 21:09:21.642380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ae51a0b5a9'
down_revision = 'e966c837caf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_favorite_games_key', 'profile', type_='unique')
    op.drop_constraint('profile_region_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_region_key', 'profile', ['region'])
    op.create_unique_constraint('profile_favorite_games_key', 'profile', ['favorite_games'])
    # ### end Alembic commands ###
