"""empty message

Revision ID: e966c837caf5
Revises: 96b4ee64d8bb
Create Date: 2022-07-07 21:03:00.715132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e966c837caf5'
down_revision = '96b4ee64d8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('like_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_user.id'], name='like_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    # ### end Alembic commands ###
