"""empty message

Revision ID: f6832627acfb
Revises: 95c061c63951
Create Date: 2022-06-24 19:44:58.803840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6832627acfb'
down_revision = '95c061c63951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('games', sa.Column('game_modes', sa.String(length=100), nullable=False))
    op.add_column('games', sa.Column('release_dates', sa.Integer(), nullable=True))
    op.drop_constraint('games_games_key', 'games', type_='unique')
    op.drop_constraint('games_genre_key', 'games', type_='unique')
    op.create_unique_constraint(None, 'games', ['name'])
    op.drop_column('games', 'games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('games', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    op.create_unique_constraint('games_genre_key', 'games', ['genre'])
    op.create_unique_constraint('games_games_key', 'games', ['games'])
    op.drop_column('games', 'release_dates')
    op.drop_column('games', 'game_modes')
    op.drop_column('games', 'name')
    # ### end Alembic commands ###
